# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b42cd529a56778e865a0db3cbc799a948e59748e7d8fd62b95645e82d2acd387665e08ddd77f29836de972d985fe2a10c259edd2483de140289b0bad1a0f135b

test:
  secret_key_base: 70db30182cb17a78ea0dddd41f335a2ca27672fad359d7f58d77534e1484c80d14e02c6522c562b312d83cce186a7819f8edb962083850d0bf9f2466e5276ef7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
